### ISSUE TITLE
k value is too high

### ISSUE THREAD

**Issue by themighty1** [mikeivanov/paillier#1]
Just curious why did you choose k value (rounds of Miller-Rabin test ) to be so high
https://github.com/mikeivanov/paillier/blob/master/primes.py#L32

As I see explained here
https://stackoverflow.com/questions/6325576/how-many-iterations-of-rabin-miller-should-i-use-for-cryptographic-safe-primes
making it 40 is good enough.

**Comment by mikeivanov** [comment]
Why so high? Well, I guess for the same reason why amateurs should not build production cryptosystems :-)

**Comment by mikeivanov** [comment]
Fixed in https://github.com/mikeivanov/paillier/commit/9aca6ced217b126aa29f5c7163291e9f93bf5355
